version: "3"
services:
  php:
    build:
      context: .
      dockerfile: php/Development/Dockerfile
    ports: 
    - "8080:80"
    networks:
      - internal
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
    volumes:
        - ./Code/:/var/www/html/
        - ./logs/:/var/log/apache2
networks:
  internal:
    driver: bridge